import type { WNA } from "../../types/wna";

export const mockWNA: WNA[] = [
  {
    id: "1",
    periode: "2026-01-08",
    jenisKelamin: "Laki-Laki",
    kewarganegaraan: "Amerika Serikat",
    noPaspor: "A1234567",
    jenisVisa: "KITAS",
    masaBerlakuVisa: "2027-06-06",
    pekerjaan: "Konsultan",
    sponsor: "AMINEF",
    kabupaten: "Belitung Timur",
    kecamatan: "Gantung",
    desa: "Lenggang",
    alamatDetail: "Jalan Lenggang Nomor 65 RT/RW.002/004",
    titikKoordinat: "47G2+JFX Padang, Kabupaten Belitung Timur, Kepulauan Bangka Belitung",
    lamaTinggal: "1 Tahun",
    statusTinggal: "Aktif",
    keterangan: "",
    sumberInformasi: "Intel POLRES Belitung Timur",
    status: "disetujui",
    approvedBy: "Kepala Bidang Keamanan",
    approvedAt: "2026-01-10T10:00:00Z",
    createdBy: "Budi Santoso",
    createdAt: "2026-01-08T08:00:00Z",
  },
  {
    id: "2",
    periode: "2026-01-14",
    jenisKelamin: "Perempuan",
    kewarganegaraan: "Australia",
    noPaspor: "PA9876543",
    jenisVisa: "Visa Pelajar",
    masaBerlakuVisa: "2026-12-31",
    pekerjaan: "Mahasiswa",
    sponsor: "Universitas Bangka Belitung",
    kabupaten: "Belitung Timur",
    kecamatan: "Manggar",
    desa: "Kurnia Jaya",
    alamatDetail: "Jalan Raya Manggar No. 45",
    titikKoordinat: "-2.8833, 108.2667",
    lamaTinggal: "2 Tahun",
    statusTinggal: "Aktif",
    keterangan: "Sedang menempuh program S2",
    sumberInformasi: "Imigrasi Belitung Timur",
    status: "disetujui",
    approvedBy: "Kabid Intelijen",
    approvedAt: "2026-01-15T09:00:00Z",
    createdBy: "Siti Rahayu",
    createdAt: "2026-01-14T14:00:00Z",
  },
  {
    id: "3",
    periode: "2026-02-01",
    jenisKelamin: "Laki-Laki",
    kewarganegaraan: "Tiongkok",
    noPaspor: "G55512345",
    jenisVisa: "KITAP",
    masaBerlakuVisa: "2028-03-15",
    pekerjaan: "Pengusaha",
    sponsor: "PT. Maju Bersama",
    kabupaten: "Belitung Timur",
    kecamatan: "Kelapa Kampit",
    desa: "Mayang",
    alamatDetail: "Jalan Industri No. 10",
    titikKoordinat: "-2.7500, 108.1800",
    lamaTinggal: "3 Tahun",
    statusTinggal: "Aktif",
    keterangan: "Pemilik usaha tambang",
    sumberInformasi: "Dinas Penanaman Modal",
    status: "menunggu",
    createdBy: "Ahmad Fauzi",
    createdAt: "2026-02-01T10:00:00Z",
  },
  {
    id: "4",
    periode: "2026-03-20",
    jenisKelamin: "Laki-Laki",
    kewarganegaraan: "Malaysia",
    noPaspor: "A12345678",
    jenisVisa: "Visa Kunjungan",
    masaBerlakuVisa: "2026-04-01",
    pekerjaan: "Wisatawan",
    sponsor: "-",
    kabupaten: "Belitung Timur",
    kecamatan: "Dendang",
    desa: "Dendang",
    alamatDetail: "Hotel Bintang Timur, Kamar 205",
    titikKoordinat: "-2.9500, 108.1500",
    lamaTinggal: "30 Hari",
    statusTinggal: "Habis Izin",
    keterangan: "Visa kunjungan sudah habis, belum ada perpanjangan",
    sumberInformasi: "Laporan Hotel",
    status: "draft",
    createdBy: "Rudi Hartono",
    createdAt: "2026-03-20T16:00:00Z",
  },
  {
    id: "5",
    periode: "2026-02-08",
    jenisKelamin: "Perempuan",
    kewarganegaraan: "Jepang",
    noPaspor: "TK1234567",
    jenisVisa: "Visa Kerja",
    masaBerlakuVisa: "2027-09-30",
    pekerjaan: "Tenaga Ahli",
    sponsor: "PT. Nippon Mining Indonesia",
    kabupaten: "Belitung Timur",
    kecamatan: "Simpang Pesak",
    desa: "Tanjung Batu Itam",
    alamatDetail: "Perumahan Karyawan Blok B No. 3",
    titikKoordinat: "-3.0200, 108.3100",
    lamaTinggal: "2 Tahun",
    statusTinggal: "Aktif",
    keterangan: "Tenaga ahli geologi",
    sumberInformasi: "Dinas Tenaga Kerja",
    status: "disetujui",
    approvedBy: "Kepala Bidang Keamanan",
    approvedAt: "2026-02-10T11:00:00Z",
    createdBy: "Dewi Lestari",
    createdAt: "2026-02-08T09:00:00Z",
  },
];

export const kewarganegaraanOptions = [
  "Amerika Serikat",
  "Australia",
  "Belanda",
  "Inggris",
  "Jepang",
  "Jerman",
  "Kanada",
  "Korea Selatan",
  "Malaysia",
  "Perancis",
  "Singapura",
  "Tiongkok",
  "Lainnya",
];

export const jenisVisaOptions = [
  "KITAS",
  "KITAP",
  "Visa Kunjungan",
  "Visa Wisata",
  "Visa Dinas",
  "Visa Diplomatik",
  "Visa Pelajar",
  "Visa Kerja",
  "Lainnya",
];

export const statusTinggalOptions = ["Aktif", "Keluar", "Habis Izin", "Lainnya"];
