import type { TKA } from "../../types/tka";

export const mockTKA: TKA[] = [
  {
    id: "1",
    periode: "2025-01-01",
    namaTKA: "CHIN HENG CHOY",
    jenisKelamin: "Laki-Laki",
    namaPerusahaan: "PT. BENUA BELTIM BERSAMA",
    jabatanKeterampilan: "Direktur",
    noTelepon: "021-30027133",
    kewarganegaraan: "Malaysia",
    noPaspor: "A1234567",
    nomorIMTA: "IMTA001",
    tanggalMulaiIMTA: "2025-01-01",
    tanggalBerakhirIMTA: "2025-12-31",
    jenisIzinTinggal: "KITAS",
    kabupaten: "Belitung Timur",
    kecamatan: "Manggar",
    desa: "Baru",
    alamatDetail: "Dusun Baru Nomor 70 RT/TW.001/006",
    titikKoordinat: "47G2+JFX Padang, Kabupaten Belitung Timur, Kepulauan Bangka Belitung",
    keterangan: "",
    sumberInformasi: "Intel POLRES Belitung Timur",
    status: "disetujui",
    approvedBy: "Kepala Bidang Keamanan",
    approvedAt: "2025-01-05T10:00:00Z",
    createdBy: "Budi Santoso",
    createdAt: "2025-01-03T08:00:00Z",
  },
  {
    id: "2",
    periode: "2025-03-01",
    namaTKA: "ZHANG WEI",
    jenisKelamin: "Laki-Laki",
    namaPerusahaan: "PT. MAJU TAMBANG INDONESIA",
    jabatanKeterampilan: "Ahli Geologi",
    noTelepon: "0812-3456-7890",
    kewarganegaraan: "Tiongkok",
    noPaspor: "G55512345",
    nomorIMTA: "IMTA002",
    tanggalMulaiIMTA: "2025-03-01",
    tanggalBerakhirIMTA: "2026-02-28",
    jenisIzinTinggal: "KITAS",
    kabupaten: "Belitung Timur",
    kecamatan: "Kelapa Kampit",
    desa: "Mayang",
    alamatDetail: "Jalan Industri No. 10 Blok B",
    titikKoordinat: "-2.7500, 108.1800",
    keterangan: "Tenaga ahli bidang eksplorasi mineral",
    sumberInformasi: "Dinas Tenaga Kerja Belitung Timur",
    status: "disetujui",
    approvedBy: "Kabid Intelijen",
    approvedAt: "2025-03-05T09:00:00Z",
    createdBy: "Siti Rahayu",
    createdAt: "2025-03-03T14:00:00Z",
  },
  {
    id: "3",
    periode: "2025-06-01",
    namaTKA: "TANAKA HIROSHI",
    jenisKelamin: "Laki-Laki",
    namaPerusahaan: "PT. NIPPON MINING INDONESIA",
    jabatanKeterampilan: "Manajer Operasional",
    noTelepon: "0811-9876-5432",
    kewarganegaraan: "Jepang",
    noPaspor: "TK1234567",
    nomorIMTA: "RPTKA003",
    tanggalMulaiIMTA: "2025-06-01",
    tanggalBerakhirIMTA: "2027-05-31",
    jenisIzinTinggal: "KITAP",
    kabupaten: "Belitung Timur",
    kecamatan: "Simpang Pesak",
    desa: "Tanjung Batu Itam",
    alamatDetail: "Perumahan Karyawan Blok A No. 5",
    titikKoordinat: "-3.0200, 108.3100",
    keterangan: "Perpanjangan KITAP ke-2",
    sumberInformasi: "Imigrasi Belitung Timur",
    status: "menunggu",
    createdBy: "Ahmad Fauzi",
    createdAt: "2025-06-02T10:00:00Z",
  },
  {
    id: "4",
    periode: "2025-09-15",
    namaTKA: "SARAH JOHNSON",
    jenisKelamin: "Perempuan",
    namaPerusahaan: "PT. GLOBAL KONSULTAN INDONESIA",
    jabatanKeterampilan: "Konsultan Lingkungan",
    noTelepon: "0813-1111-2222",
    kewarganegaraan: "Amerika Serikat",
    noPaspor: "US9876543",
    nomorIMTA: "IMTA004",
    tanggalMulaiIMTA: "2025-09-15",
    tanggalBerakhirIMTA: "2026-09-14",
    jenisIzinTinggal: "KITAS",
    kabupaten: "Belitung Timur",
    kecamatan: "Gantung",
    desa: "Lenggang",
    alamatDetail: "Jalan Lenggang No. 20",
    titikKoordinat: "-2.8500, 108.2000",
    keterangan: "Proyek AMDAL tambang timah",
    sumberInformasi: "Dinas Lingkungan Hidup",
    status: "draft",
    createdBy: "Rudi Hartono",
    createdAt: "2025-09-15T16:00:00Z",
  },
  {
    id: "5",
    periode: "2025-11-01",
    namaTKA: "PARK JI-HO",
    jenisKelamin: "Perempuan",
    namaPerusahaan: "PT. KOREA TECH BELITUNG",
    jabatanKeterampilan: "Insinyur Elektrikal",
    noTelepon: "0822-3333-4444",
    kewarganegaraan: "Korea Selatan",
    noPaspor: "M12345678",
    nomorIMTA: "RPTKA005",
    tanggalMulaiIMTA: "2025-11-01",
    tanggalBerakhirIMTA: "2026-10-31",
    jenisIzinTinggal: "Visa",
    kabupaten: "Belitung Timur",
    kecamatan: "Dendang",
    desa: "Dendang",
    alamatDetail: "Hotel Bintang Timur, Kamar 301",
    titikKoordinat: "-2.9500, 108.1500",
    keterangan: "Penugasan sementara pemasangan panel surya",
    sumberInformasi: "Laporan Perusahaan",
    status: "disetujui",
    approvedBy: "Kepala Bidang Keamanan",
    approvedAt: "2025-11-03T11:00:00Z",
    createdBy: "Dewi Lestari",
    createdAt: "2025-11-01T09:00:00Z",
  },
];

export const kewarganegaraanOptions = [
  "Amerika Serikat",
  "Australia",
  "Belanda",
  "India",
  "Inggris",
  "Jepang",
  "Jerman",
  "Kanada",
  "Korea Selatan",
  "Malaysia",
  "Perancis",
  "Singapura",
  "Tiongkok",
  "Lainnya",
];

export const jenisIzinTinggalOptions = ["Visa", "KITAS", "KITAP"];
